jobs:
- job: Test
  pool:
    vmImage: 'windows-2019'
  steps:
  - pwsh: Uninstall-Package -Name docker -ProviderName DockerMsftProvider
  - pwsh: Uninstall-Module -Name DockerMsftProvider
  - script: call configure-docker.cmd
  - script: docker run --rm --isolation=hyperv alpine ls

