jobs:
- job: Test
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: call configure-docker.cmd
  - script: docker run --rm --isolation=process alpine ls
  - script: docker run --rm --isolation=hyperv alpine ls
