jobs:
- job: Test
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: "DISM /Online /Enable-Feature /All /FeatureName:Microsoft-Hyper-V"
  - script: "DISM /online /get-features /format:table"
  #- script: call configure-docker.cmd
  #- script: docker run --rm alpine ls

