jobs:
- job: Test
  pool:
    vmImage: 'windows-2019'
  steps:
  - pwsh: Stop-Service docker
  - bash: echo $'{\n    "experimental": true\n}' | tee "/c/ProgramData/Docker/config/daemon.json";
  - bash: choco install docker-desktop -y
  - bash: docker-compose -f mysql.yml up -d
